// Theme.qml
pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

QtObject {
    id: root

    readonly property int radius: 10
    readonly property string fontFamily: "JetBrainsMono Nerd Font"
    property string iconFont: "JetBrainsMono Nerd Font"
    readonly property int animFast: 120
    readonly property int animMed: 220
    readonly property int animSlow: 380

    // Colors follow the wallpaper palette (pywal, regenerated by apply-palette.sh);
    // accent is color4, the same slot the rest of the desktop uses.
    property var wal: ({})
    readonly property var _c: wal.colors || ({})
    readonly property var _s: wal.special || ({})

    property color _bgBase: _s.background || '#0a0a0a'
    property color _fg: _s.foreground || '#ffffff'
    property color bg: alpha(_bgBase, 0.87)
    property color text: _fg
    property color textDim: mix(_fg, _bgBase, 0.35)
    property color textFaint: mix(_fg, _bgBase, 0.65)
    property color danger: _c.color1 || '#ff003c'
    property color accent: _c.color4 || '#ffffff'
    property color accent2: _c.color12 || accent
    property color ok: _c.color2 || '#00ff9c'

    property color border: mix(accent, _bgBase, 0.75)
    property color borderAccent: mix(accent, _bgBase, 0.5)
    property color bgPanel: mix(_fg, _bgBase, 0.97)
    property color bgCard: mix(_fg, _bgBase, 0.94)
    property color trackBg: mix(_fg, _bgBase, 0.88)

    function alpha(c, a) {
        return Qt.rgba(c.r, c.g, c.b, a)
    }

    // t = 0 gives a, t = 1 gives b.
    function mix(a, b, t) {
        return Qt.rgba(a.r + (b.r - a.r) * t, a.g + (b.g - a.g) * t, a.b + (b.b - a.b) * t, 1)
    }

    property FileView walFile: FileView {
        path: Quickshell.env("HOME") + "/.cache/wal/colors.json"
        watchChanges: true
        printErrors: false
        onFileChanged: reload()
        onLoaded: {
            try {
                root.wal = JSON.parse(text())
            } catch (e) {
                console.warn("Theme.qml: malformed wal colors.json: " + e)
            }
        }
    }
}
