# Zen is the main browser; Notion web apps run in it too (notion.nix).
{ pkgs, zen-browser, ... }:

let
  zenPackages = zen-browser.packages.${pkgs.stdenv.hostPlatform.system};

  # Light theme from 07:00 to 16:00, dark otherwise. Firefox reads autoconfig
  # (zen-schedule.cfg) at startup with chrome privileges; a repeating timer flips
  # the default of ui.systemUsesDarkTheme, which Zen applies live.
  autoconfigJs = pkgs.writeText "zen-schedule.js" ''
    pref("general.config.filename", "zen-schedule.cfg");
    pref("general.config.obscure_value", 0);
    pref("general.config.sandbox_enabled", false);
  '';
  mozillaCfg = pkgs.writeText "zen-schedule.cfg" ''
    // Zen light/dark schedule, generated by Nix (browser.nix).
    var zenSchedule = {
      lightFrom: 7,
      darkFrom: 16,
      apply() {
        const hour = new Date().getHours();
        const dark = hour < this.lightFrom || hour >= this.darkFrom ? 1 : 0;
        const prefs = Services.prefs.getDefaultBranch("");
        if (prefs.getIntPref("ui.systemUsesDarkTheme", -1) !== dark) {
          prefs.setIntPref("ui.systemUsesDarkTheme", dark);
        }
      },
    };
    zenSchedule.apply();
    zenSchedule.timer = Cc["@mozilla.org/timer;1"].createInstance(Ci.nsITimer);
    zenSchedule.timer.initWithCallback(
      () => zenSchedule.apply(),
      60 * 1000,
      Ci.nsITimer.TYPE_REPEATING_SLACK
    );
  '';

  # Policies must live in the unwrapped package: Zen resolves its binary
  # through the wrapper's symlink and only reads distribution/policies.json
  # next to the real executable, so `beta.override { extraPolicies }` is
  # silently ignored. The same goes for autoconfig. Wrap it the same way the
  # flake's wrap-zen.nix does.
  zenUnwrapped = (zenPackages.beta-unwrapped.override {
    extraPolicies = {
      DisableTelemetry = true;
      DontCheckDefaultBrowser = true;
      Preferences = builtins.mapAttrs (_: value: { Value = value; Status = "default"; }) {
        # Follow ui.systemUsesDarkTheme, which zen-schedule.cfg sets by time of day.
        "browser.theme.content-theme" = 2;
        "browser.theme.toolbar-theme" = 2;
        "zen.view.compact.enable" = true;
        "zen.view.compact.hide-tabbar" = true;
        "zen.view.compact.hide-toolbar" = false;
        "font.name.sans-serif.x-western" = "Inter";
        "font.name.sans-serif.x-cyrillic" = "Inter";
        "font.name.serif.x-western" = "Inter";
        "font.name.serif.x-cyrillic" = "Inter";
        "browser.tabs.unloadOnLowMemory" = true;
        # Hide the "Pop out this video" hover button; PiP stays in the context menu.
        "media.videocontrols.picture-in-picture.video-toggle.enabled" = false;
      };
      ExtensionSettings."uBlock0@raymondhill.net" = {
        installation_mode = "normal_installed";
        install_url = "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi";
      };
    };
  }).overrideAttrs (old: {
    postInstall = (old.postInstall or "") + ''
      libDir=$(echo "$out"/lib/zen-bin-*)
      # The tarball is copied from the read-only store source.
      chmod u+w "$libDir" "$libDir/defaults" "$libDir/defaults/pref"
      install -Dm644 ${autoconfigJs} "$libDir/defaults/pref/zen-schedule.js"
      install -Dm644 ${mozillaCfg} "$libDir/zen-schedule.cfg"
    '';
  });

  zen = pkgs.wrapFirefox
    (zenUnwrapped // { version = zenUnwrapped.firefoxVersion or "9999"; })
    {
      inherit (zenUnwrapped) version;
      icon = "zen-browser";
    };
in
{
  home.packages = [ zen ];
}
