# WINDOW WIDTH 
[ui.window.box]
width = 450
min_width = 100
max_width = 450
height = 50
min_height = 20
max_height = 100

# WINDOW HEIGHT
[ui.window.box.scroll.list]
height = 20
min_height = 20
max_height = 250
width = 30
min_width = 30
max_width = 30
[ui.window.box.scroll.list.item.icon]
pixel_size = 20

[ui.window.box.scroll.list.item]
h_align = "start"
min_width = 10
width = 10
max_width = 300
